# Generated by Django 5.2.5 on 2025-09-07 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailservices", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={
                "permissions": [
                    ("can_view_all_clients", "Может просматривать всех получателей")
                ],
                "verbose_name": "Получатель рассылки",
                "verbose_name_plural": "Получатели рассылки",
            },
        ),
        migrations.AlterModelOptions(
            name="message",
            options={
                "permissions": [
                    ("can_view_all_messages", "Может просматривать все сообщения")
                ],
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
            },
        ),
        migrations.AlterModelOptions(
            name="sending",
            options={
                "permissions": [
                    ("can_view_all_sendings", "Может просматривать все рассылки")
                ],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
        migrations.AlterField(
            model_name="sending",
            name="recipients",
            field=models.ManyToManyField(
                to="mailservices.client",
                verbose_name="Получатели рассылки (для добавления нескольких удерживайте CTRL)",
            ),
        ),
    ]
